Django_Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('admin_app.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.main, name='main'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact_details/', views.contact_details, name='contact_details'),
    path('reservation_data/', views.reservation_data, name='reservation_data'),
    path('get_time_slots/', views.get_time_slots, name='get_time_slots'),
    path('send_confirmation_email/', views.send_confirmation_email, name='send_confirmation_email'),
    path('reservation_check_email/', views.reservation_check_email, name='reservation_check_email'),
    path('reservation_confirmed/<str:uidb64>/<str:token>/', views.reservation_confirmed, name='reservation_confirmed'),
    path('confirm_reservation/<str:uidb64>/<str:token>/', views.confirm_reservation, name='confirm_reservation'),
    path('check_reservation/', views.check_reservation, name='check_reservation'),
    path('reservation_delete/', views.reservation_delete, name='reservation_delete')

]

users/models.py
from django.db import models
from django.utils.crypto import get_random_string


class Reservation(models.Model):
    client_name = models.CharField(max_length=255)
    client_email = models.EmailField(unique=True)
    client_phone = models.CharField(max_length=20)
    table_number = models.IntegerField(default=None)
    number_of_guests = models.IntegerField()
    reservation_time = models.TimeField()
    reservation_time_end = models.TimeField()
    reservation_date = models.DateField()
    confirmed = models.BooleanField(default=False)
    confirmed_visit = models.BooleanField(default=False)
    uidb64 = models.CharField(max_length=64, blank=True)
    token = models.CharField(max_length=64, blank=True)

    def save(self, *args, **kwargs):
        if not self.uidb64:
            self.uidb64 = get_random_string(64)
        if not self.token:
            self.token = get_random_string(64)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.client_name


class Table(models.Model):
    number = models.IntegerField()
    capacity = models.IntegerField()

users/forms.py
from django import forms

from .models import Reservation


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = (
            'client_name',
            'client_email',
            'client_phone',
            'table_number',
            'number_of_guests',
            'reservation_time',
            'reservation_time_end',
            'reservation_date'
        )

users/views.py
from datetime import datetime, timedelta

import json

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str

from .forms import ReservationForm
from .logic.time_slot_select import time_slot_select
from .logic.time_and_date import  working_days
from .models import Reservation, Table
from .token import reservation_token_generator


def main(request):
    return render(request, 'main.html')


def contact_details(request):
    reservation_date = working_days()
    if request.method == 'POST':
        client_name = request.POST.get('client_name')
        client_email = request.POST.get('client_email')
        client_phone = request.POST.get('client_phone')
        number_of_guests = request.POST.get('number_of_guests')
        reservation_date = request.POST.get('reservation_date')

        request.session['client_name'] = client_name
        request.session['client_email'] = client_email
        request.session['client_phone'] = client_phone
        request.session['number_of_guests'] = number_of_guests
        request.session['reservation_date'] = reservation_date
        return redirect('users:reservation_data')
    return render(request, 'contact_details.html', {'reservation_date': reservation_date})


def reservation_data(request):
    client_email = request.session.get('client_email')
    email = Reservation.objects.filter(client_email=client_email)

    # The choice of tables according to their capacity, depending on the number of guests
    guests = request.session.get('number_of_guests')
    tables = Table.objects.filter(capacity__gte=guests, capacity__lte=str(int(guests) + 2))

    tables = [table.number for table in tables]
    if request.method == 'POST':
        client_name = request.session.get('client_name')
        client_email = request.session.get('client_email')
        client_phone = request.session.get('client_phone')
        number_of_guests = request.session.get('number_of_guests')
        reservation_date = request.session.get('reservation_date')

        table_number = request.POST.get('table_number')
        reservation_time = request.POST.get('reservation_time')
        reservation_time_end = (datetime.strptime(reservation_time, '%H:%M') + timedelta(hours=1)).time()
        data = {
            'client_name': client_name,
            'client_email': client_email,
            'client_phone': client_phone,
            'number_of_guests': number_of_guests,
            'reservation_date': reservation_date,
            'table_number': table_number,
            'reservation_time': reservation_time,
            'reservation_time_end': reservation_time_end
        }

        form = ReservationForm(data)
        if form.is_valid():
            reservation = Reservation.objects.create(**data)
            request.session['reservation_id'] = reservation.pk
            return redirect('users:send_confirmation_email')

    return render(request, 'reservation_data.html', {'tables': tables, 'email': email})


def get_time_slots(request):
    # generating and passing time slots to the time_slots.js script so that when the user
    # selects a table number, the corresponding time slots are displayed without reloading the page

    if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        data = json.loads(request.body)
        table_id = data.get('table_id')

        reservation_date = request.session.get('reservation_date')

        available_time_slots, max_end_time = time_slot_select(table_id, reservation_date)

        return JsonResponse({'time_slots': available_time_slots,
                             'max_end_time': max_end_time.strftime('%H:%M') if max_end_time else None})

    return JsonResponse({'error': 'Invalid request'}, safe=False)


def send_confirmation_email(request):
    reservation_id = request.session.get('reservation_id')
    reservation = Reservation.objects.get(pk=reservation_id)
    subject = 'Booking confirmation'
    from_email = settings.EMAIL_HOST_USER
    to_email = reservation.client_email

    current_site = get_current_site(request)
    uid = urlsafe_base64_encode(force_bytes(reservation.id))
    token = reservation_token_generator.make_token(reservation)

    email_message = render_to_string('reservation_confirmation_email.html', {
        'reservation': reservation,
        'domain': current_site.domain,
        'uid': uid,
        'token': token,
    })
    send_mail(subject, email_message, from_email, [to_email], html_message=email_message)

    return redirect('users:reservation_check_email')


def confirm_reservation(request, uidb64, token):
    uid = force_str(urlsafe_base64_decode(uidb64))
    reservation = get_object_or_404(Reservation, id=uid)
    if not reservation.confirmed and reservation_token_generator.check_token(reservation, token):
        reservation.confirmed = True
        reservation.save()
        return redirect('users:reservation_confirmed', uidb64=uidb64, token=token)

    return render(request, 'reservation_not_found.html')


def reservation_check_email(request):
    return render(request, 'reservation_check_email.html')


def reservation_confirmed(request, uidb64, token):
    uid = force_str(urlsafe_base64_decode(uidb64))
    reservation = get_object_or_404(Reservation, id=uid)

    return render(request, 'reservation_confirmed.html', {'reservation': reservation})


def check_reservation(request):
    if request.method == 'POST':
        email = request.POST.get('client_email')
        reservation = Reservation.objects.filter(client_email=email)

        if reservation:
            return render(request, 'check_reservation.html', {'reservation': reservation})
        else:
            return render(request, 'reservation_not_found.html')


def reservation_delete(request):
    email = request.GET.get('client_email')
    Reservation.objects.filter(client_email=email).delete()
    return render(request, 'reservation_delete.html', {'email': email})


def about_us(request):
    return render(request, 'about_us.html')

users/templates/about_us.html
{% extends 'base.html' %}


{% block content %}
    <div class="center">
        <h1>Restaurant of European cuisine Django.</h1><br>
        <h1>Delicious food, refreshing drinks and more. It's definitely worth a visit :)</h1>
    </div>
{% endblock %}

users/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Django Restaurant</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="/static/style.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
	<header>
		<h1>Django Restaurant</h1>
		<nav>
			<a href="/" style="font-size: 20px;">Main</a>
			<a href="/about_us" style="font-size: 20px;">About us</a>
		</nav>
	</header>

	{% block content %}
	{% endblock %}

	<footer class="contacts">
		<p>Street: Warsaw, Main Street 123</p>
		<p>Phone: +48 432112340</p>
		<p>Email: django.restaurant.reservation@gmail.com</p>
	</footer>
</body>
</html>

users/templates/check_reservation.html
{% extends 'base.html' %}

{% block content %}
<div class="center">
{% for sub_reservation in reservation.values %}
  {% if sub_reservation.confirmed == 1 %}
    <h1>Your reservation:</h1>
    <br>
    {% for reserv in reservation %}
        <p style="font-size: 18px;">Name: {{ reserv.client_name }}</p>
        <p style="font-size: 18px;">Email: {{ reserv.client_email }}</p>
        <p style="font-size: 18px;">Phone: {{ reserv.client_phone }}</p>
        <p style="font-size: 18px;">Table number: {{ reserv.table_number }}</p>
        <p style="font-size: 18px;">Number of guests: {{ reserv.number_of_guests }}</p>
        <p style="font-size: 18px;">Date: {{ reserv.reservation_date }}</p>
        <p style="font-size: 18px;">Time: {{ reserv.reservation_time }}</p>

        <br>
        <a href="{% url 'users:reservation_delete' %}?client_email={{ reserv.client_email }}" class="button" style="font-size: 16px;">Delete a Reservation</a>
        <br>
        <br>
        <br>
    {% endfor %}
  {% else %}
    <h1>Reservation not confirmed!</h1>
  {% endif %}
{% endfor %}
</div>
{% endblock %}

users/templates/contact_details.html
{% extends "base.html" %}

{% block content %}
  <h1 style="text-align: center;">Contact Information </h1>
  <form method="post" action="{% url 'users:contact_details' %}">
  {% csrf_token %}

  <div class="form-group">
    <label for="client_name">Name:</label>
    <input type="text" class="form-control" id="client_name" name="client_name" placeholder="Enter your name" required>
  </div>
  <div class="form-group">
    <label for="client_email">E-mail:</label>
    <input type="email" class="form-control" id="client_email" name="client_email" placeholder="Enter your e-mail" required>
  </div>
  <div class="form-group">
    <label for="client_phone">Phone:</label>
    <input type="tel" class="form-control" id="client_phone" name="client_phone" placeholder="Enter your телефон" required>
  </div>
  <div class="form-group">
    <label for="number_of_guests">Number of guests:</label>
    <input type="number" class="form-control" id="number_of_guests" name="number_of_guests" placeholder="Enter Введите number of guests" required>
  </div>
  <div class="form-group">
      <label for="reservation_date">Reservation date:</label>
      <select name="reservation_date" id="reservation_date">
        {% for date in reservation_date %}
          <option value="{{ date }}">{{ date }}</option>
        {% endfor %}
      </select>
  </div>

  <div style="display: flex; justify-content: center;">
    <button type="submit">Next</button>
  </div>
  </form>

{% endblock %}

users/templates/main.html
{% extends 'base.html' %}


{% block content %}
    <div class="center">
        <a href="{% url 'users:contact_details' %}" class="button">Make a Reservation</a>
        <form method="post" action="{% url 'users:check_reservation' %}">
            {% csrf_token %}
            <input type="email" id="client_email" name="client_email" required placeholder="Enter your email" style="height: 70px;">
            <button type="submit" class="btn btn-success">Check Reservation</button>
        </form>
    </div>
{% endblock %}

users/templates/reservation_check_email.html
{% extends 'base.html' %}

{% block content %}
    <div style="text-align: center; margin-top: 30px;">
        <h1>Check your mail</h1><br>
        <p style="font-size: 20px;">We have emailed you to confirm your reservation. Please check your email and follow the instructions in the email.</p>
    </div>
{% endblock %}

users/templates/reservation_confirmation_email.html
{% load static %}

<h2 style="text-align: center;">Reservation confirmation</h2>

<p style="text-align: center;">To confirm your reservation, please click on the link below:</p>

<a href="http://{{ domain }}{% url 'users:confirm_reservation' uidb64=uid token=token %}" style="display: inline-block; text-align: center;">Confirm</a>

users/templates/reservation_confirmed.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if reservation.confirmed %}
    <h1 style="text-align: center; margin-top: 30px;">Booking confirmed</h1>
    <p style="text-align: center; font-size: 22px; margin-top: 20px;">Table number: {{ reservation.table_number }}</p>
    <p style="text-align: center; font-size: 22px;">Date: {{ reservation.reservation_date }}</p>
    <p style="text-align: center; font-size: 22px;">Time: {{ reservation.reservation_time }}</p>
{% else %}
    <h1>Booking confirmation error</h1>
{% endif %}

{% endblock %}

users/templates/reservation_data.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if email %}
  <h1>This mail is already taken</h1>
{% else %}
  <h1 style="text-align: center;">Table reservation</h1>
  <header>
    <style>
      .logo {
        display: block;
        margin: 0 auto;
        max-width: 50%;
        height: auto;
        margin-bottom: 20px;
      }

      .form-container {
        text-align: center;
        margin-top: 20px;
      }

      .form-container form {
        display: inline-block;
        margin: 0 10px;
      }

      .form-group {
        display: inline-block;
        margin: 0 10px;
      }
    </style>
    <img class="logo" src="{% static 'restaurant_tables.jpg' %}" alt="Restaurant tables">
  </header>

  <div class="form-container">
    <form method="post" action="">
      {% csrf_token %}
      <div class="form-group">
        <label for="table_number">Choose a table:</label>
        <select id="table_number" name="table_number">
          {% for table in tables %}
            <option value="{{ table }}">{{ table }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="form-group" id="time_slots_container">
        <label for="reservation_time">Choose a time:</label>
        <select id="reservation_time" name="reservation_time" required>
          <option value="" disabled selected hidden>First choose a table</option>
        </select>
      </div>


      <button type="submit">Make a reservation</button>
    </form>
  </div>


  {% block scripts %}
    <script src="{% static 'js/time_slots.js' %}"></script>
  {% endblock %}
{% endif %}
{% endblock %}

users/templates/reservation_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="center">
        <h1>
            Reservation to e-mail<br><br>
            {{email}}<br><br>
            has been successfully deleted<br>
        </h1>
    </div>
{% endblock %}

users/templates/reservation_not_found.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1 class="center">Reservation not found</h1>
{% endblock %}