Django_Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('admin_app.urls')),
]

admin_app/urls.py
from django.urls import path
from . import views

app_name = 'admin_app'

urlpatterns = [
    path('admin_reservations/', views.admin_reservations, name='admin_reservations'),
    path('admin_reservation_detail/<int:reservation_id>/', views.admin_reservation_detail, name='admin_reservation_detail'),
    path('admin_confirm_visit/<int:reservation_id>/', views.admin_confirm_visit, name='admin_confirm_visit'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.main, name='main'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact_details/', views.contact_details, name='contact_details'),
    path('reservation_data/', views.reservation_data, name='reservation_data'),
    path('get_time_slots/', views.get_time_slots, name='get_time_slots'),
    path('send_confirmation_email/', views.send_confirmation_email, name='send_confirmation_email'),
    path('reservation_check_email/', views.reservation_check_email, name='reservation_check_email'),
    path('reservation_confirmed/<str:uidb64>/<str:token>/', views.reservation_confirmed, name='reservation_confirmed'),
    path('confirm_reservation/<str:uidb64>/<str:token>/', views.confirm_reservation, name='confirm_reservation'),
    path('check_reservation/', views.check_reservation, name='check_reservation'),
    path('reservation_delete/', views.reservation_delete, name='reservation_delete')

]

admin_app/views.py
from django.shortcuts import render, redirect, get_object_or_404

from admin_app.logic.reservation_table import reservation_table
from users.models import Reservation


def admin_reservations(request):
    """
    The function creates a table where columns are time slots and rows are table numbers.
    The cells in the table show whether there is a corresponding reservation or not.
    The table is created for the selected date
    """

    if not request.user.is_authenticated:
        return redirect('admin:index')
    else:
        selected_date = request.GET.get('date')
        if selected_date:
            reservations = Reservation.objects.filter(reservation_date=selected_date).order_by('table_number',
                                                                                               'reservation_time')
        else:
            reservations = Reservation.objects.none()

        reservation_list, time_slots = reservation_table(reservations)

        context = {
            'reservation_list': reservation_list,
            'time_slots': time_slots,
            'selected_date': selected_date,
        }

        return render(request, 'admin_reservations.html', context)


def admin_reservation_detail(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    context = {'reservation': reservation}
    return render(request, 'admin_reservation_detail.html', context)


def admin_confirm_visit(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    reservation.confirmed_visit = True
    reservation.save()
    return redirect('admin_app:admin_reservations')

admin_app/templates/admin_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Django Restaurant</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="/static/style.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
	<header>
		<h1>Django Restaurant Admin</h1>
		<nav>
			<a href="/admin_reservations/" style="font-size: 20px;">Reservations</a>
		</nav>
	</header>

	{% block content %}
	{% endblock %}

</body>
</html>

admin_app/templates/admin_reservation_detail.html
{% extends 'admin_base.html' %}

{% block content %}
    <h1  style="text-align: center;margin-top: 30px;">Reservation details</h1>
        <p  style="text-align: center; font-size: 18px;">Client name: {{ reservation.client_name }}</p>
        <p  style="text-align: center; font-size: 18px; margin-top: 20px;">Table number: {{ reservation.table_number }}</p>
        <p  style="text-align: center; font-size: 18px;">Time: {{ reservation.reservation_time }}</p>
{% endblock %}

admin_app/templates/admin_reservations.html
{% extends 'admin_base.html' %}

{% block content %}
<style>
    table {
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid black;
        padding: 20px;
    }
    .reservation-table {
        margin-top: 50px;
    }
</style>

    <form class="center" method="get" action="">
        <label for="date">Select a date:</label>
        <input type="date" id="date" name="date" value="{{ selected_date }}">
        <button type="submit">Show</button>
    </form>

    <table class="reservation-table">
        <thead>
            <tr>
                <th>Table number</th>
                {% for time_slot in time_slots %}
                    <th>{{ time_slot }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for table_index, table_row in reservation_list %}
                <tr>
                    <td>{{ table_index }}</td>
                    {% for reservation in table_row %}
                        {% if reservation %}
                            <td>
                                {{ reservation.client_name }}
                                <br>
                                {% if reservation.id %}
                                    <a href="{% url 'admin_app:admin_reservation_detail' reservation.id %}">More</a>
                                {% endif %}
                                <br>
                                {% if reservation.id and not reservation.confirmed_visit%}
                                    <a href="{% url 'admin_app:admin_confirm_visit' reservation.id %}">Confirm</a>
                                {% endif %}
                            </td>
                        {% else %}
                            <td>---</td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}